language: go

go:
  - "1.10"

script:
  - go get -v -t github.com/ah8ad3/gateway
  - sh build/build.sh

before_deploy:
- export TRAVIS_TAG="0.3.$TRAVIS_BUILD_NUMBER"
- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
- git config --local user.name "$USER_NAME"
- git config --local user.email "$USER_EMAIL"
- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"


deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "dist/gateway"
  skip_cleanup: true
  on:
    tags: false
